blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/nix-community/ethereum.nix/discussions
    about: Have a question or need help? Connect with the community on our discussion board