name: Build and Check
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ | Checkout
        uses: actions/checkout@v2.3.1

      - name: â„ï¸ | Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: ğŸ”Œ | Link Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ethereum-nix
          authToken: "${{ secrets.ETHEREUM_NIX_CACHE_KEY }}"

      - name: ğŸ” | Check
        run: |
          nix flake check

      - name: ğŸš | Run Shell
        run: |
          nix develop
